// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaptqsllaxhiwandsexv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphcHRxc2xsYXhoaXdhbmRzZXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTY2OTEsImV4cCI6MjA2Nzk3MjY5MX0.srrasWyZvVjEDhIqfdNVDnB3jaK33xXY8EZfkzwhsHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});